#!/bin/bash

# Check if arguments are provided
if [ $# -lt 6 ]; then
    echo "Usage: $0 <tech_count> <health_count> <finance_count> <education_count> <sports_count> <politics_count>"
    exit 1
fi

# Assign arguments to variables
tech_count=$1
health_count=$2
finance_count=$3
education_count=$4
sports_count=$5
politics_count=$6

# Define arrays of titles and content for each category

# Technology
phrases_technology_titles=("The latest technology news" "Discover cutting-edge innovations" "Explore the future of tech" "The rise of AI" "Blockchain and its applications")
phrases_technology_content=("Technology is evolving at an unprecedented pace. Every day, new innovations and breakthroughs are changing the way we live and work.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. " 
                            "Artificial Intelligence (AI) is one of the most exciting fields in technology today. AI has the potential to transform industries and improve our daily lives.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                            "Blockchain technology is revolutionizing the way we think about security and transparency. From cryptocurrencies to smart contracts, blockchain is here to stay.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                            "The Internet of Things (IoT) is connecting devices and systems in ways we never thought possible. From smart homes to connected cars, IoT is making our lives more convenient and efficient.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                            "Augmented Reality (AR) and Virtual Reality (VR) are changing the way we interact with the world around us. From gaming to education, AR and VR are creating new experiences and opportunities.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. ")

# Health
phrases_health_titles=("Latest health updates" "New breakthroughs in medicine" "Tips for a healthy lifestyle" "Mental health awareness" "Nutrition and wellness")
phrases_health_content=("Staying healthy is essential for a happy and fulfilling life. From regular exercise to a balanced diet, there are many ways to maintain good health.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                        "Mental health is just as important as physical health. It's important to take care of your mind and seek help if you need it.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                        "Advances in medical research are leading to new treatments and cures for diseases. It's an exciting time for the medical field.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                        "Nutrition plays a vital role in our overall health and well-being. Eating a balanced diet can help prevent diseases and improve your quality of life.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                        "Regular exercise is crucial for maintaining good health. Whether it's a daily walk or a vigorous workout, staying active can benefit your body and mind.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. ")

# Finance
phrases_finance_titles=("Finance news and updates" "Investment strategies for 2024" "Economic trends to watch" "Personal finance tips" "Understanding the stock market")
phrases_finance_content=("The stock market can be a volatile and unpredictable place, but with the right strategies, you can make informed investment decisions.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                         "Understanding economic trends is crucial for making sound financial decisions. Keep an eye on interest rates, inflation, and other key indicators.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                         "Personal finance management is essential for achieving your financial goals. From budgeting to saving, there are many ways to take control of your finances.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                         "Investment strategies vary depending on your goals and risk tolerance. It's important to diversify your portfolio and stay informed about market trends.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                         "The global economy is constantly changing, and staying informed is key to making sound financial decisions.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. ")

# Education
phrases_education_titles=("Innovations in education" "The future of online learning" "Tips for students" "Educational resources" "Lifelong learning opportunities")
phrases_education_content=("Education is constantly evolving, and new technologies are making it more accessible and effective than ever before.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                           "Online learning has become increasingly popular, offering flexibility and convenience for students of all ages.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                           "There are many resources available to help students succeed, from tutoring services to online courses.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                           "Lifelong learning is important for personal and professional growth. It's never too late to learn something new.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                           "Innovative teaching methods are transforming the classroom and making learning more engaging and interactive.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. ")

# Sports
phrases_sports_titles=("Exciting sports updates" "Get the latest scores" "Follow your favorite teams" "In-depth sports analysis" "The impact of sports on society")
phrases_sports_content=("Sports bring people together and create a sense of community and pride.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                        "Keeping up with the latest scores and updates is essential for any sports fan.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                        "Following your favorite teams and players can be a fun and rewarding experience.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                        "In-depth analysis of games and players can provide valuable insights and enhance your understanding of the sport.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                        "Sports have a significant impact on society, from promoting physical fitness to bringing people together.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. ")

# Politics
phrases_politics_titles=("Breaking political news" "Stay informed about current events" "Analysis of key issues" "The impact of policy changes" "Political debates and discussions")
phrases_politics_content=("Politics plays a crucial role in shaping our society and impacting our daily lives.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                          "Staying informed about current events and political developments is important for making informed decisions.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                          "In-depth analysis of key issues can provide valuable insights and help you understand the complexities of the political landscape.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                          "Policy changes can have a significant impact on various aspects of society, from the economy to healthcare.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. "
                          "Political debates and discussions are essential for a healthy democracy and informed citizenry.Donec molestie posuere lectus eu fermentum. Vivamus pharetra purus ac finibus mollis. Etiam pulvinar elementum luctus. Donec suscipit rutrum mattis. Duis placerat sed lectus in malesuada. Integer semper lobortis odio ut gravida. Donec ultrices tellus in mauris viverra ultrices. Proin venenatis vitae velit eu rutrum. Donec vel vulputate tellus. Cras rhoncus libero in urna sollicitudin euismod. Proin in libero ultrices, interdum felis sit amet, porttitor odio. Morbi et mi tortor. Donec pretium tristique lorem et imperdiet.

Proin elementum pellentesque dictum. Integer non faucibus justo. Nullam euismod pellentesque nisi, id tincidunt erat mollis sed. Donec pellentesque non risus nec faucibus. Vivamus mollis erat et pulvinar ultricies. Fusce nec velit non tellus molestie efficitur nec et velit. Morbi tempor rutrum erat, non lobortis erat ultrices vitae.

Donec mattis quis lectus at ullamcorper. Aenean in elit tempor, placerat nisl eget, feugiat lorem. Maecenas vehicula porta justo, at blandit augue porta vitae. Duis finibus consectetur diam, eget volutpat justo vehicula elementum. Curabitur nec nibh libero. Mauris ultrices lectus id libero suscipit, quis vulputate massa consectetur. Proin eget sapien eu elit vestibulum dictum non vel quam. Praesent magna dolor, tincidunt nec iaculis in, sodales et velit. Nulla vel dapibus quam. Sed consequat eget tellus tempor venenatis. Duis interdum at sem non posuere. Quisque in semper ante. Aenean et elementum ipsum. Nullam id purus libero.

Pellentesque finibus, orci id efficitur semper, enim turpis bibendum mi, nec rutrum dui dui vel nisi. Aenean non dolor nec mi fermentum scelerisque. Phasellus dapibus malesuada nisi id auctor. Nullam sagittis, lacus sed feugiat gravida, orci eros accumsan velit, nec malesuada nisl arcu vitae lacus. Donec imperdiet orci justo, eu pharetra lorem gravida et. Nullam cursus sapien et rhoncus placerat. Nulla mauris purus, congue eget metus nec, pretium porta dui. Suspendisse erat ex, vulputate non nisi sed, consectetur luctus turpis.

Vestibulum pellentesque in lacus eu volutpat. Duis venenatis dolor scelerisque, feugiat lacus a, imperdiet mauris. Pellentesque malesuada congue enim, quis eleifend dolor dapibus id. Pellentesque elementum, nunc eu aliquam ultricies, eros lectus gravida mauris, id vehicula massa lorem ut quam. Curabitur non luctus urna, id varius diam. Proin ac mauris justo. Ut eu mattis nunc. Morbi non nulla in velit egestas tristique. Sed sit amet tellus eleifend, iaculis arcu et, posuere mi. Vestibulum id aliquam nulla, id rutrum leo. Vestibulum porttitor eget eros sit amet mattis. Fusce aliquam eros lobortis commodo tincidunt. Phasellus congue tincidunt turpis, rutrum venenatis metus scelerisque et. ")

# Create a subdirectory for sample documents
mkdir -p sample_documents

# Function to generate documents
generate_documents() {
    local count=$1
    local titles=("${!2}")
    local contents=("${!3}")
    local category=$4

    mkdir -p "sample_documents/$category"
    for ((i=1; i<=count; i++)); do
        index=$((i % ${#titles[@]}))
        title="${titles[$index]}"
        content="${contents[$index]}"
        echo -e "$title\n\n$content" > "sample_documents/$category/document_$i.txt"
    done
}

# Generate documents for each category
generate_documents $tech_count phrases_technology_titles[@] phrases_technology_content[@] "technology"
generate_documents $health_count phrases_health_titles[@] phrases_health_content[@] "health"
generate_documents $finance_count phrases_finance_titles[@] phrases_finance_content[@] "finance"
generate_documents $education_count phrases_education_titles[@] phrases_education_content[@] "education"
generate_documents $sports_count phrases_sports_titles[@] phrases_sports_content[@] "sports"
generate_documents $politics_count phrases_politics_titles[@] phrases_politics_content[@] "politics"

echo "Sample documents generated successfully in sample_documents directory."
